server:
  port: 8002

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    url: jdbc:mysql://192.168.96.20:3306/mydatabase
    password: 123456
    #password: root
    #url: jdbc:mysql://localhost:3306/mydatabase
    #driver-class-name: org.gjt.mm.mysql.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zhangzc.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

  instance:
    instance-id: payment-service8002
    prefer-ip-address: true