server:
  port: 9101

spring:
  application:
    name: provider-nacos-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.96.20:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'