server:
  port: 80
spring:
  application:
    name: consumer-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.96.20:8848
        register-enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

rpc:
  uri: http://provider-nacos-payment
