server:
  port: 8001

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://192.168.96.20:3306/mydatabase
    #driver-class-name: org.gjt.mm.mysql.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zhangzc.springcloud.entities