server:
  port: 8006

spring:
  application:
    name: payment-hystrix-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: payment-service8001
    prefer-ip-address: true